/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.User;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import service.AuthService;
import model.User;
import exception.AuthenticationException;
import exception.DatabaseException;
import db.DatabaseConnection;
import java.sql.Connection;
import java.util.logging.Logger;
/**
 *
 * @author Gabriel Prakosa A
 */
public class CustomerDashboard extends javax.swing.JPanel {

    /**
     * Creates new form DashboardCustomer
     */
    public CustomerDashboard(User user) {
        initComponents();
    }

    public CustomerDashboard(MainFrame mainFrame, User user) {
        this(user); // Call the default constructor to initialize components
        // Additional initialization with mainFrame and user if needed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboardCustomer = new javax.swing.JLabel();
        btnPesanMakanan = new javax.swing.JButton();
        btnKeranjangPesanan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        lblDashboardCustomer.setText("Halaman Dashboard Customer");

        btnPesanMakanan.setText("Pesan Makanan");
        btnPesanMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanMakananActionPerformed(evt);
            }
        });

        btnKeranjangPesanan.setText("Keranjang Pesanan");
        btnKeranjangPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeranjangPesananActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDashboardCustomer)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPesanMakanan)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnKeranjangPesanan)
                        .addGap(132, 132, 132))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblDashboardCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnPesanMakanan)
                .addGap(18, 18, 18)
                .addComponent(btnKeranjangPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanMakananActionPerformed

    private void btnKeranjangPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeranjangPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeranjangPesananActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeranjangPesanan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPesanMakanan;
    private javax.swing.JLabel lblDashboardCustomer;
    // End of variables declaration//GEN-END:variables
}
