/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import ui.MainFrame;
import model.User;

/**
 *
 * @author Gabriel Prakosa A
 */
public class DashboardCustomer extends javax.swing.JPanel {

    /**
     * Creates new form DashboardCustomer
     */
    public DashboardCustomer() {
        initComponents();
    }

    public DashboardCustomer(MainFrame mainFrame, User user) {
        this(); // Call the default constructor to initialize components
        // Additional initialization with mainFrame and user if needed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboardCustomer = new javax.swing.JLabel();
        btnPesanMakanan = new javax.swing.JButton();
        btnKeranjangPesanan = new javax.swing.JButton();
        btnTopUpEwallet = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        lblDashboardCustomer.setText("Halaman Dashboard Customer");

        btnPesanMakanan.setText("Pesan Makanan");
        btnPesanMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanMakananActionPerformed(evt);
            }
        });

        btnKeranjangPesanan.setText("Keranjang Pesanan");
        btnKeranjangPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeranjangPesananActionPerformed(evt);
            }
        });

        btnTopUpEwallet.setText("Top Up E-wallet");
        btnTopUpEwallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpEwalletActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDashboardCustomer)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPesanMakanan)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnTopUpEwallet))
                            .addComponent(btnKeranjangPesanan))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblDashboardCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnPesanMakanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeranjangPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTopUpEwallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesanMakananActionPerformed

    private void btnKeranjangPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeranjangPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeranjangPesananActionPerformed

    private void btnTopUpEwalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopUpEwalletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopUpEwalletActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        MainFrame.setUser(null); // reset user
        MainFrame.showPanel(new LoginForm(MainFrame));
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeranjangPesanan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPesanMakanan;
    private javax.swing.JButton btnTopUpEwallet;
    private javax.swing.JLabel lblDashboardCustomer;
    // End of variables declaration//GEN-END:variables
}
