/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.User;

/**
 *
 * @author Gabriel Prakosa A
 */
public class DashboardAdmin extends javax.swing.JPanel {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }

    public DashboardAdmin(MainFrame mainFrame, User user) {
        this(); // Call the default constructor to initialize components
        // Additional initialization with mainFrame and user if needed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboardAdmin = new javax.swing.JLabel();
        btnCRUDRestaurantMenuItem = new javax.swing.JButton();
        btnCRUDAkunCustomer = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        lblDashboardAdmin.setText("halaman Dashboard Admin");

        btnCRUDRestaurantMenuItem.setText("Edit Restaurant dan Menu");
        btnCRUDRestaurantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDRestaurantMenuItemActionPerformed(evt);
            }
        });

        btnCRUDAkunCustomer.setText("Edit Akun Customer");
        btnCRUDAkunCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDAkunCustomerActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDashboardAdmin)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCRUDRestaurantMenuItem)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCRUDAkunCustomer)
                        .addGap(129, 129, 129))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblDashboardAdmin)
                .addGap(26, 26, 26)
                .addComponent(btnCRUDRestaurantMenuItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCRUDAkunCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRUDRestaurantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDRestaurantMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCRUDRestaurantMenuItemActionPerformed

    private void btnCRUDAkunCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDAkunCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCRUDAkunCustomerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDAkunCustomer;
    private javax.swing.JButton btnCRUDRestaurantMenuItem;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel lblDashboardAdmin;
    // End of variables declaration//GEN-END:variables
}
