/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.*;
import java.util.logging.Logger;

/**
 * Dashboard untuk pengguna dengan role admin.
 * Author: Gabriel Prakosa A
 */
public class AdminDashboard extends javax.swing.JPanel {
    private static final Logger LOGGER = Logger.getLogger(AdminDashboard.class.getName());
    private final MainFrame mainFrame;
    private final CardLayout cardLayout;

    public AdminDashboard(MainFrame mainFrame, CardLayout cardLayout) {
        this.mainFrame = mainFrame;
        this.cardLayout = cardLayout;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDashboardAdmin = new javax.swing.JLabel();
        btnCRUDRestaurantMenuItem = new javax.swing.JButton();
        btnCRUDAkunCustomer = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Halaman Dashboard Admin", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblDashboardAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnCRUDRestaurantMenuItem.setText("Edit Restaurant dan Menu");
        btnCRUDRestaurantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDRestaurantMenuItemActionPerformed(evt);
            }
        });

        btnCRUDAkunCustomer.setText("Edit Akun Customer");
        btnCRUDAkunCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRUDAkunCustomerActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblDashboardAdmin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnCRUDRestaurantMenuItem)))
                .addGap(0, 101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCRUDAkunCustomer)
                        .addGap(124, 124, 124))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblDashboardAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnCRUDRestaurantMenuItem)
                .addGap(18, 18, 18)
                .addComponent(btnCRUDAkunCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRUDRestaurantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDRestaurantMenuItemActionPerformed
        LOGGER.info("Navigating to AddRestaurantMenu panel.");
        mainFrame.showRestaurantMenuPanel();
    }//GEN-LAST:event_btnCRUDRestaurantMenuItemActionPerformed

    private void btnCRUDAkunCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRUDAkunCustomerActionPerformed
        LOGGER.info("Navigating to EditUserPanel.");
        mainFrame.showEditUserPanel();
    }//GEN-LAST:event_btnCRUDAkunCustomerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LOGGER.info("Logout button clicked.");
        mainFrame.showLoginPanel();
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRUDAkunCustomer;
    private javax.swing.JButton btnCRUDRestaurantMenuItem;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDashboardAdmin;
    // End of variables declaration//GEN-END:variables
}
