/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.User;
import javax.swing.*;
import java.util.logging.Logger;
import service.CartService;
import java.awt.*;
import java.awt.FlowLayout;
import java.awt.BorderLayout;

/**
 * Dashboard untuk pengguna dengan role customer.
 * Author: Gabriel Prakosa A
 */
public class CustomerDashboard extends javax.swing.JPanel {
    private static final Logger LOGGER = Logger.getLogger(CustomerDashboard.class.getName());
    private final MainFrame mainFrame;
    private final User user;
    private CartService cartService;
    private JLabel cartBadgeLabel;
    private JLabel lblBalance; // Added for balance display

    public CustomerDashboard(MainFrame mainFrame, User user) {
        this.mainFrame = mainFrame;
        this.user = user;
        this.cartService = new CartService();
        initComponents();
        initializeCartBadge();
        initializeBalanceLabel(); // Initialize balance label
        updateCartBadge();
        refreshUserBalance(); // Update balance display
        
        LOGGER.info("CustomerDashboard initialized for user: " + user.getUsername());
    }

    private void initializeCartBadge() {
        cartBadgeLabel = new JLabel();
        cartBadgeLabel.setOpaque(true);
        cartBadgeLabel.setBackground(Color.RED);
        cartBadgeLabel.setForeground(Color.WHITE);
        cartBadgeLabel.setHorizontalAlignment(SwingConstants.CENTER);
        cartBadgeLabel.setBorder(BorderFactory.createEmptyBorder(2, 6, 2, 6));
        cartBadgeLabel.setFont(new Font("Arial", Font.BOLD, 10));
        cartBadgeLabel.setVisible(false);
        
        btnKeranjangPesanan.setLayout(new BorderLayout());
        JPanel badgePanel = new JPanel();
        badgePanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 0, 0));
        badgePanel.setOpaque(false);
        badgePanel.add(cartBadgeLabel);
        btnKeranjangPesanan.add(badgePanel, BorderLayout.NORTH);
    }

    private void initializeBalanceLabel() {
        lblBalance = new JLabel();
        lblBalance.setFont(new Font("Arial", Font.PLAIN, 12));
        lblBalance.setHorizontalAlignment(SwingConstants.CENTER);
        jPanel1.add(lblBalance); // Add to panel
    }

    public void updateCartBadge() {
        SwingUtilities.invokeLater(() -> {
            try {
                int itemCount = cartService.getCartForCustomer(user.getId()).getItems().size();
                if (itemCount > 0) {
                    cartBadgeLabel.setText(String.valueOf(itemCount));
                    cartBadgeLabel.setVisible(true);
                } else {
                    cartBadgeLabel.setVisible(false);
                }
                btnKeranjangPesanan.repaint();
            } catch (Exception e) {
                LOGGER.warning("Failed to update cart badge: " + e.getMessage());
                cartBadgeLabel.setVisible(false);
            }
        });
    }

    public void refreshUserBalance() {
        SwingUtilities.invokeLater(() -> {
            try {
                lblBalance.setText(String.format("Saldo E-Wallet: Rp %.0f | Saldo Rekening: Rp %.0f", 
                        user.getEwalletBalance(), user.getRekeningBalance()));
                lblBalance.repaint();
                
                LOGGER.info("User balance refreshed for: " + user.getUsername());
            } catch (Exception e) {
                LOGGER.warning("Failed to refresh user balance: " + e.getMessage());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDashboardCustomer = new javax.swing.JLabel();
        btnPesanMakanan = new javax.swing.JButton();
        btnKeranjangPesanan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Halaman Dashboard Customer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnPesanMakanan.setText("Pesan Makanan");
        btnPesanMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanMakananActionPerformed(evt);
            }
        });

        btnKeranjangPesanan.setText("Keranjang Pesanan");
        btnKeranjangPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeranjangPesananActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lblDashboardCustomer)
                .addGap(18, 18, 18)
                .addComponent(btnPesanMakanan)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeranjangPesanan)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnPesanMakanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashboardCustomer)
                .addGap(16, 16, 16)
                .addComponent(btnKeranjangPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesanMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanMakananActionPerformed
        LOGGER.info("Pesan Makanan button clicked for user: " + user.getUsername());
        mainFrame.showPilihMakananPanel(user);
    }//GEN-LAST:event_btnPesanMakananActionPerformed

    private void btnKeranjangPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeranjangPesananActionPerformed
        LOGGER.info("Keranjang Pesanan button clicked for user: " + user.getUsername());
        mainFrame.showKeranjangPanel(user);
    }//GEN-LAST:event_btnKeranjangPesananActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LOGGER.info("Logout button clicked for user: " + user.getUsername());
        mainFrame.showLoginPanel();
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeranjangPesanan;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPesanMakanan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDashboardCustomer;
    // End of variables declaration//GEN-END:variables
}
